networks:
  jupyterhub:
    name: jupyterhub
    
services:
  kaggle:
    # 로컬 빌드시
    image: teddylee777/docker-kaggle-ko:latest
    volumes:
        # local 폴더:도커폴더 를 입력합니다.(예시: /data/jupyter:/home/jupyter)
        # 도커 생성시 /home/jupyter가 생성되어 있으므로 그냥 놔두어도 OK
      - /data/jupyter:/home/jupyter
    restart: always
    ports:
        # Jupyter notebook port 번호 지정, ssh 포트 필요시 지정
        # local 포트:도커 포트
      - "8888:8888"
      - "22:22" # ssh

  jupyterhub:
    image: kwater22/jupyterhub
    build:
      context: ./04-JupyterHub
      dockerfile: jupyterhub.Dockerfile
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JUPYTERHUB_MOUNT_DIR=D://deepko//data
    ports:
      - "10030:8000"
    networks:
      - jupyterhub
      